### ISSUE TITLE
Love the software, question about encoding

### ISSUE THREAD

**Issue by pacid** [yhegde/fb-page-scraper#1]
Hello :)
Thanks for this piece of software, really useful and easy to use. Had a scrapper in minutes just running!

One issue I have is that I'm getting a lot of exceptions like this one:
java.sql.SQLException: Incorrect string value: '\xF0\x9F\x94\xA5\xF0\x9F...' for column 'message' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2113)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2049)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2034)
	at common.Post.updatePost(Post.java:164)
	at common.Post.updateDb(Post.java:135)
	at common.PostsCollector.collect(PostsCollector.java:90)
	at common.PostsCollector.collect(PostsCollector.java:97)
	at common.PostsCollector.collect(PostsCollector.java:97)
	at common.PostsCollector.collect(PostsCollector.java:97)
	at common.PostsCollector.collect(PostsCollector.java:97)
	at common.PostsCollector.collect(PostsCollector.java:97)
	at common.PostsCollector.collect(PostsCollector.java:97)
	at common.PostsCollector.collect(PostsCollector.java:97)
	at common.PostsCollector.collect(PostsCollector.java:97)
	at common.PostsCollector.collect(PostsCollector.java:45)
	at cmdline.FbCollector.collectOnce(FbCollector.java:60)
	at cmdline.FbCollector.main(FbCollector.java:42)

when my table for Posts:

-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Mar 30, 2016 at 09:52 PM
-- Server version: 5.5.46-0ubuntu0.14.04.2
-- PHP Version: 5.5.9-1ubuntu4.5

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `whatever`
--

-- --------------------------------------------------------

--
-- Table structure for table `Post`
--

CREATE TABLE IF NOT EXISTS `Post` (
  `id` varchar(255) NOT NULL,
  `page_id` varchar(255) NOT NULL,
  `message` text,
  `created_at` datetime NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `likes` int(11) DEFAULT '0',
  `comments` int(11) DEFAULT '0',
  `shares` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `fk_page_id_idx` (`page_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `Post`
--
ALTER TABLE `Post`
  ADD CONSTRAINT `fk_page_id` FOREIGN KEY (`page_id`) REFERENCES `Page` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

and also I've added into my.cnf

[client]
default-character-set=utf8

[mysql]
default-character-set=utf8

[mysqld]
collation-server = utf8_unicode_ci
init-connect='SET NAMES utf8'
character-set-server = utf8

Any clues?

**Comment by pacid** [comment]
OK, found the solution here:
http://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc  ( madtracy's answer, point 1)

Better to use utf8mb4.

Hope this help someone
